language: c++
before-install:
  - sudo apt-get -y update
  - sudo apt-get -y install software-properties-common
  - sudo apt-get -y install libpng12-0
  - sudo apt-get -y install libpng12-dev
  - sudo apt-get -y install curl
  - sudo apt-get -y install gcc
  - sudo apt-get -y install g++
  - sudo apt-get -y install scons
  - sudo apt-get -y install automake
  - sudo apt-get -y install autoconf
  - sudo apt-get -y install libperl4-corelibs-perl
  - sudo apt-get -y install libtool
  - sudo apt-get -y install xorg-dev
  - sudo apt-get -y install doxygen
  - sudo apt-get -y install python-dev
  - sudo apt-get -y install alien
  - sudo apt-get -y install swig
  - sudo apt-get -y install libgtest-dev
  - sudo apt-get -y install libstdc++6
  - sudo apt-get -y install libxml2-dev
  - sudo apt-get -y install gettext
  - sudo apt-get -y install libxinerama-dev
  - sudo apt-get -y install libxft-dev
  - sudo apt-get -y install libxrandr-dev
  - sudo apt-get -y install libxcursor-dev
  - sudo apt-get -y install libgdbm-dev
  - sudo apt-get -y install libc6
  - sudo apt-get -y install libc6-dev
  - sudo apt-get -y install libmng-dev
  - sudo apt-get -y install zlib1g-dev
  - sudo apt-get -y install libcap-dev
  - sudo apt-get -y install freeglut3-dev
  - sudo apt-get -y install flex
  - sudo apt-get -y install libx11-dev
  - sudo apt-get -y install bison++
  - sudo apt-get -y install bisonc++
  - sudo apt-get -y install libjpeg-dev
  - sudo apt-get -y install libjpeg8-dev
  - sudo apt-get -y install python2.7
  - sudo apt-get -y install python2.7-dev
  - sudo apt-get -y install libogdi3.2-dev
  - sudo apt-get -y install libgif-dev
  - sudo apt-get -y install libxerces-c-dev
  - sudo apt-get -y install libgeos-dev
  - sudo apt-get -y install libgeos++-dev
  - sudo apt-get -y install libfreetype6
  - sudo apt-get -y install libfreetype6-dev
  - sudo apt-get -y install python-imaging
  - sudo apt-get -y install libproj-dev
  - sudo apt-get -y install python-setuptools
  - sudo apt-get -y install libgif-dev
  - sudo apt-get -y install libxerces-c-dev
  - sudo apt-get -y install libcap-dev
  - sudo apt-get -y install libpq-dev
  - sudo apt-get -y install openssl
git:
  lfs_skip_smudge: true
script: ./build.sh
